<Project>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest</AnalysisLevel>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>zer0day.ro</Authors>
    <Company>zer0day.ro</Company>
    <Product>zdtllmcli</Product>
    <Copyright>Copyright (c) zer0day.ro</Copyright>
    <PackageProjectUrl>https://zer0day.ro</PackageProjectUrl>
    <RepositoryUrl>https://zer0day.ro</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

</Project>
