<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Zdtllm.Mcp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Zdtllm.Tools\Zdtllm.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Zdtllm.Core.Tests" />
  </ItemGroup>

</Project>
